apiVersion: v1
kind: Secret
metadata:
  name: smartshop-secrets
  namespace: smartshop
type: Opaque
data:
  # Base64 encoded values:
  # admin -> YWRtaW4=
  db-username: YWRtaW4=
  db-password: YWRtaW4=
  
  # Base64 encoded SQS Queue URL (Real SQS URL from Terraform output)
  sqs-queue-url: aHR0cHM6Ly9zcXMuZXUtd2VzdC0xLmFtYXpvbmF3cy5jb20vNDgxNjY1MTMwNjYwL3NtYXJ0c2hvcC1kZXYtcXVldWU=
